/** PRODUCTS */
export const PRODUCTS_SUBSCRIPTION_READY = 'PRODUCTS_SUBSCRIPTION_READY';
export const PRODUCTS_SUBSCRIPTION_CHANGED = 'PRODUCTS_SUBSCRIPTION_CHANGED';
export const PRODUCTS = 'products';

export const PRODUCT_SUBSCRIPTION_READY = 'PRODUCT_SUBSCRIPTION_READY';
export const PRODUCT_SUBSCRIPTION_CHANGED = 'PRODUCT_SUBSCRIPTION_CHANGED';
export const PRODUCT = 'product';
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

/** PROPERTY GROUPS */
export const PROPERTY_GROUPS_SUBSCRIPTION_READY = 'PROPERTY_GROUPS_SUBSCRIPTION_READY';
export const PROPERTY_GROUPS_SUBSCRIPTION_CHANGED = 'PROPERTY_GROUPS_SUBSCRIPTION_CHANGED';
export const PROPERTY_GROUPS = 'property_groups';

export const ADD_PROPERTY_GROUP_REQUEST = 'ADD_PROPERTY_GROUP_REQUEST';
export const ADD_PROPERTY_GROUP_FAILURE = 'ADD_PROPERTY_GROUP_FAILURE';
export const DELETE_PROPERTY_GROUP_REQUEST = 'DELETE_PROPERTY_GROUP_REQUEST';
export const DELETE_PROPERTY_GROUP_FAILURE = 'DELETE_PROPERTY_GROUP_FAILURE';
export const UPDATE_PROPERTY_GROUP_REQUEST = 'UPDATE_PROPERTY_GROUP_REQUEST';
export const UPDATE_PROPERTY_GROUP_FAILURE = 'UPDATE_PROPERTY_GROUP_FAILURE';

/** PROPERTIES */
export const PROPERTIES_SUBSCRIPTION_READY = 'PROPERTIES_SUBSCRIPTION_READY';
export const PROPERTIES_SUBSCRIPTION_CHANGED = 'PROPERTIES_SUBSCRIPTION_CHANGED';
export const PROPERTIES = 'properties';

export const ADD_PROPERTY_REQUEST = 'ADD_PROPERTY_REQUEST';
export const ADD_PROPERTY_FAILURE = 'ADD_PROPERTY_FAILURE';
export const DELETE_PROPERTY_REQUEST = 'DELETE_PROPERTY_REQUEST';
export const DELETE_PROPERTY_FAILURE = 'DELETE_PROPERTY_FAILURE';
export const UPDATE_PROPERTY_REQUEST = 'UPDATE_PROPERTY_REQUEST';
export const UPDATE_PROPERTY_FAILURE = 'UPDATE_PROPERTY_FAILURE';

/** FILTERS */
export const FILTERS_SUBSCRIPTION_READY = 'FILTERS_SUBSCRIPTION_READY';
export const FILTERS_SUBSCRIPTION_CHANGED = 'FILTERS_SUBSCRIPTION_CHANGED';
export const FILTERS = 'filters';
export const FILTER_SUBSCRIPTION_READY = 'FILTER_SUBSCRIPTION_READY';
export const FILTER_SUBSCRIPTION_CHANGED = 'FILTER_SUBSCRIPTION_CHANGED';
export const FILTER = 'filter';
export const UPDATE_FILTER_REQUEST = 'UPDATE_FILTER_REQUEST';
export const DELETE_FILTER_REQUEST = 'DELETE_FILTER_REQUEST';
export const ADD_FILTER_REQUEST = 'ADD_FILTER_REQUEST';
export const ADD_FILTER_FAILURE = 'ADD_FILTER_FAILURE';