/** PRODUCTS */
export const PRODUCTS_SUBSCRIPTION_READY = 'PRODUCTS_SUBSCRIPTION_READY';
export const PRODUCTS_SUBSCRIPTION_CHANGED = 'PRODUCTS_SUBSCRIPTION_CHANGED';
export const PRODUCTS = 'products';

export const PRODUCT_SUBSCRIPTION_READY = 'PRODUCT_SUBSCRIPTION_READY';
export const PRODUCT_SUBSCRIPTION_CHANGED = 'PRODUCT_SUBSCRIPTION_CHANGED';
export const PRODUCT = 'product';
export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

/** MODALS */
export const MODAL_TYPE_CONFIRM = 'MODAL_TYPE_CONFIRM';
export const MODAL_TYPE_ALERT = 'MODAL_TYPE_ALERT';
export const MODAL_TYPE_REGISTER = 'MODAL_TYPE_REGISTER';
export const MODAL_TYPE_LOGIN = 'MODAL_TYPE_LOGIN';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

/** USER */
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

/** CART */
export const CART_SUBSCRIPTION_READY = 'CART_SUBSCRIPTION_READY';
export const CART_SUBSCRIPTION_CHANGED = 'CART_SUBSCRIPTION_CHANGED';
export const CART = 'cart';

export const CART_ADD_PRODUCT_REQUEST = 'CART_ADD_PRODUCT_REQUEST';
export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS';